##config
project_folder : /path/to/project_folder
ngs_bits_folder : /path/to/ngs_bits_folder
meta_data: /path/to/metadata.txt
bams : /path/to/test_bams
bed : /path/to/bed/Twist_panBRCA_hg38.bed
ref_fa : /path/to/genome/GRCh38.fa
out_folder : /path/to/output_folder
Methyldackel_path : /path/to/MethylDackel
